# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    leg_intact_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

leg_controller:
  ros__parameters:
    joints:
      - vertical_rail_to_mount
      - knee_joint
      - ankle_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
leg_intact_controller:
  ros__parameters:
    joints:
      - vertical_rail_to_mount_intact
      - knee_joint_intact
      - ankle_joint_intact
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity