# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    jetleg_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

jetleg_controller:
  ros__parameters:
    joints:
      - knee_joint
      - ankle_joint
    interface_name: effort
    state_interfaces:
      - position
      - velocity

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu0
    frame_id: shank_imu