# MoveIt uses this configuration for controller management

# NOTE: This must be assigned true when using simulation
use_sim_time: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - jetleg_controller
    - jetleg_intact_controller

  jetleg_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - vertical_rail_to_mount
      - knee_joint
      - ankle_joint
    action_ns: follow_joint_trajectory
    default: true
  jetleg_intact_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - vertical_rail_to_mount_intact
      - knee_joint_intact
      - ankle_joint_intact