/jetleg_pointcloud_proc:
  ros__parameters:

    x_min:                  -1.0
    x_max:                  1.0

    y_min:                  -1.0
    y_max:                  1.5

    Z_MIN:                  0.5
    Z_MAX:                  2.0

    resolution:             80