<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="jetleg_intact">

    <xacro:property name="thigh_intact_length" value="0.3" />
    <xacro:property name="shank_intact_length" value="0.3" />
    <xacro:property name="knee_intact_joint_radius" value="0.025" />
    <xacro:property name="ankle_intact_joint_radius" value="0.025" />
    <xacro:property name="foot_intact_length" value="0.3" />
    <xacro:property name="foot_intact_width" value="0.1" />
    <xacro:property name="foot_intact_height" value="0.05" />

    <link name="thigh_intact">
        <visual>
            <geometry>
                <cylinder length="${thigh_intact_length}" radius="0.06"/>
            </geometry>
            <material name="white"/> 
        </visual>
        <collision>
            <geometry>
                <cylinder length="${thigh_intact_length}" radius="0.06"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="10"/>
            <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
        </inertial>
    </link>

    <link name="shank_intact">
        <visual>
            <geometry>
                <cylinder length="${shank_intact_length}" radius="0.06"/>
            </geometry>
            <material name="white"/> 
            <origin rpy="0 0 0" xyz="0 0 ${-shank_intact_length/2-knee_intact_joint_radius}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${shank_intact_length}" radius="0.06"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 ${-shank_intact_length/2-knee_intact_joint_radius}"/>
        </collision>
        <inertial>
            <mass value="10"/>
            <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
            <origin rpy="0 0 0" xyz="0 0 ${-shank_intact_length/2-knee_intact_joint_radius}"/>
        </inertial>
    </link>

    <joint name="knee_intact_joint" type="revolute">
        <origin rpy="0 0 0" xyz="0 0 ${-thigh_intact_length/2-knee_intact_joint_radius}"/>
        <parent link="thigh_intact"/>
        <child link="shank_intact"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" lower="0.0" upper="1.5" velocity="10"/>
    </joint>

    <link name="foot_intact">
        <visual>
            <geometry>
                <box size="${foot_intact_length} ${foot_intact_width} ${foot_intact_height}"/>
            </geometry>
            <material name="white"/> 
            <origin xyz="${(foot_intact_length/2-0.05)} 0 ${-ankle_intact_joint_radius-foot_height/2}"/>
        </visual>
        <collision>
            <geometry>
                <box size="${foot_intact_length} ${foot_intact_width} ${foot_intact_height}"/>
            </geometry>
            <origin xyz="${(foot_intact_length/2-0.05)} 0 ${-ankle_intact_joint_radius-foot_intact_height/2}"/>
        </collision>
        <inertial>
            <mass value="10"/>
            <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
            <origin xyz="${(foot_intact_length/2-0.05)} 0 ${-ankle_intact_joint_radius-foot_intact_height/2}"/>
        </inertial>
    </link>

    <joint name="ankle_intact_joint" type="revolute">
        <origin rpy="0 0 0" xyz="0 0 ${-(knee_intact_joint_radius + shank_intact_length + ankle_intact_joint_radius)}"/>
        <parent link="shank_intact"/>
        <child link="foot_intact"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" lower="-0.1" upper="0.5" velocity="10"/>
    </joint>

</robot>