<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="jetleg">

    <xacro:property name="thigh_length" value="0.5" />
    <xacro:property name="shank_length" value="0.4" />
    <xacro:property name="knee_joint_radius" value="0.025" />
    <xacro:property name="ankle_joint_radius" value="0.025" />
    <xacro:property name="foot_length" value="0.3" />
    <xacro:property name="foot_width" value="0.1" />
    <xacro:property name="foot_height" value="0.05" />

    <xacro:property name="thigh_mass" value="20" />
    <xacro:property name="shank_mass" value="10" />
    <xacro:property name="foot_mass" value="1.5" />

    <xacro:macro name="jetleg" params="identifier">
        <link name="thigh${identifier}">
            <visual>
                <geometry>
                    <cylinder length="${thigh_length}" radius="0.06"/>
                </geometry>
                <material name="white"/> 
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${thigh_length}" radius="0.06"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${thigh_mass}"/>
                <inertia ixx="${thigh_mass/12*(3*0.06**2+thigh_length**2)}" ixy="0" ixz="0" iyy="${thigh_mass/12*(3*0.06**2+thigh_length**2)}" iyz="0" izz="${0.5*thigh_mass*0.06**2}"/>
            </inertial>
        </link>

        <link name="shank${identifier}">
            <visual>
                <geometry>
                    <cylinder length="${shank_length}" radius="0.06"/>
                </geometry>
                <material name="white"/> 
                <origin rpy="0 0 0" xyz="0 0 ${-shank_length/2-knee_joint_radius}"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${shank_length}" radius="0.06"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${-shank_length/2-knee_joint_radius}"/>
            </collision>
            <inertial>
                <mass value="${shank_mass}"/>
                <inertia ixx="${shank_mass/12*(3*0.06**2+shank_length**2)}" ixy="0" ixz="0" iyy="${shank_mass/12*(3*0.06**2+shank_length**2)}" iyz="0" izz="${0.5*shank_mass*0.06**2}"/>
                <origin rpy="0 0 0" xyz="0 0 ${-shank_length/2-knee_joint_radius}"/>
            </inertial>
        </link>

        <joint name="knee_joint${identifier}" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 ${-thigh_length/2-knee_joint_radius}"/>
            <parent link="thigh${identifier}"/>
            <child link="shank${identifier}"/>
            <axis xyz="0 1 0"/>
            <limit effort="100" lower="0.0" upper="1.5" velocity="10"/>
        </joint>

        <link name="foot${identifier}">
            <contact>
                <lateral_friction value="100"/>
            </contact>

            <visual>
                <geometry>
                    <box size="${foot_length} ${foot_width} ${foot_height}"/>
                </geometry>
                <material name="white"/> 
                <origin xyz="${(foot_length/2-0.05)} 0 ${-ankle_joint_radius-foot_height/2}"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${foot_length} ${foot_width} ${foot_height}"/>
                </geometry>
                <origin xyz="${(foot_length/2-0.05)} 0 ${-ankle_joint_radius-foot_height/2}"/>
            </collision>
            <inertial>
                <mass value="1.5"/>
                <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
                <origin xyz="${(foot_length/2-0.05)} 0 ${-ankle_joint_radius-foot_height/2}"/>
            </inertial>
        </link>

        <joint name="ankle_joint${identifier}" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 ${-(knee_joint_radius + shank_length + ankle_joint_radius)}"/>
            <parent link="shank${identifier}"/>
            <child link="foot${identifier}"/>
            <axis xyz="0 1 0"/>
            <limit effort="100" lower="-0.1" upper="0.5" velocity="10"/>
        </joint>
    </xacro:macro>

</robot>