<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="jetleg_wheeled_testrig">

    <!-- Include the basic testrig -->
    <xacro:include filename="$(find jetleg_description)/urdf/testrig.xacro"/>
    <!-- Include the JetLeg -->
    <xacro:include filename="$(find jetleg_description)/urdf/jetleg.xacro"/> 

    <!-- Define reusable variables -->
    <xacro:property name="wheel_length" value="0.04" />
    <xacro:property name="wheel_radius" value="0.15" />
    <xacro:property name="wheel_offset" value="0.4" />

    <!-- Define the wheel macro -->
    <xacro:macro name="wheel" params="wheelpos parentsupport reflect offset">
        <link name="wheel_${wheelpos}">
            <contact>
                <rolling_friction value="0.001"/>
                <spinning_friction value="0.001"/>
            </contact>
            <visual>
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                </geometry>
                <material name="white" />
            </visual>

            <collision>
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                </geometry>
                <contact_coefficients mu="1.0" />
            </collision>

            <inertial>
                <mass value="10"/>
                <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
            </inertial>
        </link>

        <joint name="wheel_${wheelpos}_joint" type="continuous">
            <parent link="support_${parentsupport}" />
            <child link="wheel_${wheelpos}" />
            <origin xyz="${offset} ${0.2 * reflect} -${gantry_height / 2}" rpy="1.57 0 0" />
            <axis xyz="0 0 -1" />
        </joint>
    </xacro:macro>

    <!-- Create four wheels for the testrig -->
    <xacro:wheel wheelpos="fore_left" parentsupport="left" reflect="1" offset="${wheel_offset}" />
    <xacro:wheel wheelpos="fore_right" parentsupport="right" reflect="-1" offset="${wheel_offset}" />

    <xacro:wheel wheelpos="hind_left" parentsupport="left" reflect="1" offset="${-wheel_offset}" />
    <xacro:wheel wheelpos="hind_right" parentsupport="right" reflect="-1" offset="${-wheel_offset}" />

    <!-- Create two JetLegs -->
    <xacro:jetleg identifier="">
    </xacro:jetleg>

    <xacro:jetleg identifier="_intact">
    </xacro:jetleg>

    <!-- Use mounts to attach legs to the testrig -->
    <link name="mount">
        <visual>
            <geometry>
                <cylinder length="${mount_length}" radius="0.08"/>
            </geometry>
            <material name="black"/> 
        </visual>
        <inertial>
                <mass value="1"/>
                <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
                <origin rpy="0 0 0" xyz="0 0 0"/>
        </inertial>
    </link>
    <gazebo reference="mount">
        <material>Gazebo/Black</material>
    </gazebo>

    <link name="mount_intact">
        <visual>
            <geometry>
                <cylinder length="${mount_length}" radius="0.08"/>
            </geometry>
            <material name="black"/> 
        </visual>
        <inertial>
                <mass value="1"/>
                <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
                <origin rpy="0 0 0" xyz="0 0 0"/>
        </inertial>
    </link>
    <gazebo reference="mount_intact">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- Define the additional joints of the robot -->

    <joint name="vertical_rail_to_mount" type="revolute">
        <origin rpy="0 0 0" xyz="0 -0.1 0"/>
        <parent link="vertical_rail"/>
        <child link="mount"/>
        <limit effort="100" lower="${-mount_angle_lim}" upper="${mount_angle_lim}" velocity="10"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="vertical_rail_to_mount_intact" type="revolute">
        <origin rpy="0 0 0" xyz="0 0.1 0"/>
        <parent link="vertical_rail"/>
        <child link="mount_intact"/>
        <limit effort="100" lower="${-mount_angle_lim}" upper="${mount_angle_lim}" velocity="10"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="mount_to_jetleg" type="fixed">
        <parent link="mount"/>
        <child link="thigh"/>
        <origin xyz="0 0 ${-thigh_length/2}" rpy="0 0 0"/>
        <axis xyz="0 0 -1" />
        <limit effort="100" velocity="10" lower="0" upper="0.6" />
    </joint>

    <joint name="mount_to_jetleg_intact" type="fixed">
        <parent link="mount_intact"/>
        <child link="thigh_intact"/>
        <origin xyz="0 0 ${-thigh_length/2}" rpy="0 0 0"/>
        <axis xyz="0 0 -1" />
        <limit effort="100" velocity="10" lower="0" upper="0.6" />
    </joint>

    <gazebo>
        <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
            <parameters>$(find jetleg_moveit_config)/config/ros2_controllers.yaml</parameters>

            <robot_param>robot_description</robot_param>
            <robot_param_node>robot_state_publisher</robot_param_node>
        </plugin>
    </gazebo>

    <xacro:include filename="$(find jetleg_description)/urdf/jetleg_imu.xacro"/> 
    <xacro:jetleg_imu />

    <joint name="shank_imu_joint" type="fixed">
        <parent link="shank"/>
        <child link="shank_imu"/>
        <origin xyz="0 0 ${-thigh_length/2-knee_joint_radius}" rpy="0 0 0"/>
    </joint>

</robot>
