<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="jetleg_testrig">

    <xacro:include filename="colors.xacro"/>

    <xacro:property name="gantry_height" value="1" />
    <xacro:property name="gantry_width" value="1.6" />
    <xacro:property name="mount_angle" value="${25*pi/180}" />
    <xacro:property name="mount_length" value="0.24" />

    <link name="base_link">
    </link>

    <link name="gantry">
        <visual>
            <geometry>
                <box size="0.05 ${gantry_width} 0.05"/>
            </geometry>
            <material name="white_transluscent"/> 
        </visual>
        <collision>
            <geometry>
                <box size="0.05 ${gantry_width} 0.05"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="100"/>
            <inertia ixx="10" ixy="0" ixz="0" iyy="10" iyz="0" izz="10"/>
        </inertial>
    </link>

    <joint name="base_to_gantry" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 ${gantry_height}"/>
        <parent link="base_link"/>
        <child link="gantry"/>
    </joint>

    <xacro:macro name="support" params="postfix reflect">
        <link name="support_${postfix}">
            <visual>
                <geometry>
                    <box size="0.5 0.25 ${gantry_height}"/>
                </geometry>
                <material name="red_transluscent"/> 
            </visual>
            <collision>
                <geometry>
                    <box size="0.5 0.25 ${gantry_height}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="1000"/>
                <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100"/>
            </inertial>
        </link>

        <joint name="gantry_to_support_${postfix}" type="fixed">
            <parent link="gantry"/>
            <child link="support_${postfix}"/>
            <origin xyz="0 ${reflect * gantry_width/2} -${gantry_height/2}" />
        </joint>
    </xacro:macro>

    <xacro:support postfix="left" reflect="1" />
    <xacro:support postfix="right" reflect="-1" />

    <joint name="gantry_to_mount" type="fixed">
        <origin rpy="0 0 0" xyz="0 0.0 0"/>
        <parent link="gantry"/>
        <child link="mount"/>
    </joint>

    <link name="mount">
        <visual>
            <geometry>
                <cylinder length="${mount_length}" radius="0.08"/>
            </geometry>
            <material name="white_transluscent"/> 
            <origin rpy="0 ${mount_angle} 0" xyz="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${mount_length}" radius="0.08"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="100"/>
            <inertia ixx="10" ixy="0" ixz="0" iyy="10" iyz="0" izz="10"/>
        </inertial>
    </link>

    <xacro:include filename="jetleg.xacro"/> 
    
    <joint name="mount_to_jetleg" type="fixed">
        <origin rpy="0 ${mount_angle} 0" xyz="${-mount_length*sin(mount_angle)/2} 0 ${-mount_length*cos(mount_angle)/2}"/>
        <parent link="mount"/>
        <child link="thigh"/>
    </joint>

</robot>