<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="testrig">

    <xacro:include filename="$(find jetleg_description)/urdf/colors.xacro"/>

    <xacro:property name="gantry_height" value="1" />
    <xacro:property name="gantry_width" value="1.6" />
    <xacro:property name="mount_angle_lim" value="${40*pi/180}" />
    <xacro:property name="mount_length" value="0.24" />

    <link name="base_link">
    </link>

    <link name="vertical_rail">
        <visual>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <material name="white"/>
        </visual>
        <inertial>
            <mass value="30"/>
            <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
        </inertial>
    </link>

    <link name="gantry">
        <visual>
            <geometry>
                <box size="0.05 ${gantry_width} 0.05"/>
            </geometry>
            <material name="white_transluscent"/> 
        </visual>
    </link>

    <xacro:macro name="support" params="postfix reflect">
        <link name="support_${postfix}">
            <visual>
                <geometry>
                    <box size="0.5 0.25 ${gantry_height}"/>
                </geometry>
                <material name="red_transluscent"/> 
            </visual>
            <collision>
                <geometry>
                    <box size="0.5 0.25 ${gantry_height}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="10000"/>
                <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100"/>
            </inertial>
        </link>

        <joint name="gantry_to_support_${postfix}" type="fixed">
            <parent link="gantry"/>
            <child link="support_${postfix}"/>
            <origin xyz="0 ${reflect * gantry_width/2} ${-gantry_height/2}" />
        </joint>
    </xacro:macro>

    <xacro:support postfix="left" reflect="1" />
    <xacro:support postfix="right" reflect="-1" />

    <joint name="base_to_gantry" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 ${gantry_height}"/>
        <parent link="base_link"/>
        <child link="gantry"/>
    </joint>

    <joint name="gantry_to_vertical_rail" type="prismatic">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="gantry"/>
        <child link="vertical_rail"/>
        <limit effort="100" lower="-1" upper="3" velocity="10"/>
        <axis xyz="0 0 1"/>
    </joint>

</robot>
