name: Build and Test
run-name: ${{ github.actor }} is building and testing the code
on: [push]
jobs:
  Build-and-Test-Action:
    runs-on: ubuntu-latest
    steps:
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        target-ros2-distro: humble
